### ISSUE TITLE
RuntimeError: normal expects all elements of std >= 0.0

### ISSUE THREAD

**Issue by shipra-madan** [wbw520/MTUNet#1]
Gives this error on cifar and all other datests, Could u plz help in this. Thanks

!python train_scouter.py --random False --interval 10 --dataset cifarfs --base_model resnet18 --channel 512 --num_classes 64 --data_root "../FSL_data"!

[58 50 12 10 44 12 41]
patterns num:  7
model name:  cifarfs_resnet18_use_slot_7checkpoint.pth
data/data_split/cifarfs/train.csv
64
data/data_split/cifarfs/train.csv
64
load pre feature extractor parameter over
Traceback (most recent call last):
  File "train_scouter.py", line 86, in <module>
    main(args, selection=selection)
  File "train_scouter.py", line 21, in main
    model = SlotModel(args)
  File "/content/MTUNet/model/scouter/scouter_model.py", line 22, in __init__
    vis_id=args.vis_id, loss_status=args.loss_status, power=args.power, to_k_layer=args.to_k_layer)
  File "/content/MTUNet/model/scouter/scouter_attention.py", line 23, in __init__
    self.initial_slots = nn.Parameter(torch.normal(mu, sigma))
RuntimeError: normal expects all elements of std >= 0.0

**Comment by wbw520** [comment]
This is a Pytorch version problem and there are two solutions for this.
1. In model/scouter/scouter_attention.py line 19  add torch.abs() outside the torch.randn(). 
2. Using torch 1.6.0 and torchvision 0.7.0

**Comment by shipra-madan** [comment]
Thanks a lot!
